### ISSUE TITLE
x86_64-elf-tools-windows.zip contains i686 tools instead of x86_64

### ISSUE THREAD

**Issue by AlectronikForge** [alessandromrc/i686-elf-tools#1]
Like the title says. I was looking for a x86_64-elf toolchain for windows and found your project. But the x86_64 archive contains only i686 tools.

**Comment by alessandromrc** [comment]
Hi, the release wasn't compiled for the x64 version but just for the 686 one, if you check the Readme you can see that there's a parameter to compile them for x64
